[build]
  command = "npm run build:simple"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.123.7"  # Updated to your current Hugo version
  HUGO_ENV = "production"
  # Cache NPM dependencies between builds
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --production=false"

# Custom domain setup
[[redirects]]
  from = "https://articles.appraisily.com/*"
  to = "/:splat"
  status = 200
  force = true

# Redirect for 404s to improve user experience
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Performance optimizations
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://ik.imagekit.io data:; connect-src 'self' https://www.google-analytics.com; frame-ancestors 'none';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[context.production]
  command = "npm run build:simple"
  [context.production.environment]
    HUGO_ENV = "production"
    # No API keys needed for simple builds that don't generate articles
    
[context.deploy-preview]
  command = "npm run build:simple"
  [context.deploy-preview.environment]
    HUGO_ENV = "production"
    # Using simple build for previews to avoid API charges
  
[context.branch-deploy]
  command = "npm run build:simple"
  [context.branch-deploy.environment]
    HUGO_ENV = "production"
    # Using simple build for branch deploys to avoid API charges

# Plugin configuration
[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "public"